### ISSUE TITLE
Backup adds subfolders for full path of source folder, instead of only the sourcefolder

### ISSUE THREAD

**Issue by zilexa** [3coma3/btrfs-backup#21]
**Describe the bug**
Instead of only creating a backup of source folder, it creates ALL folders in the path before the source folder, then the source folder and then the data. 

How can I prevent that from happening? 
![Screenshot from 2021-01-24 21-27-08](https://user-images.githubusercontent.com/3430004/105642694-7d43ea00-5e8b-11eb-8c69-321b7d96ad8c.png)

**Comment by zilexa** [comment]
I am preventing this now by moving the script and conf file to the folder that contains my source folder and calling the script from there. I also changed the .conf file, source is now simply `shanti` instead of the full path. 

Still this is cumbersome.

**Comment by 3coma3** [comment]
I thought of having the full path actually as a feature, because that way you can tell where in the original filesystem was the thing you wanted to restore or compare or whatever.

But, arguably it could be desirable to have the option to turn it off and only store the last part in case you don't care about the original location.

I'm not exactly sure this is actually something that can be directly expressed with the rsync syntax for source directories, let me investigate on this and if it isn't something that we can say directly with the source syntax, I'll add an explicit way.

**Comment by 3coma3** [comment]
Fixed by b651a16 and b8aee12
